### ISSUE TITLE
Added a way to add to the QPointCloud

### ISSUE THREAD

**Issue by kheaactua** [MASKOR/Qt3DPointcloudRenderer#3]
(not really an issue..)

I added a method to add to the QPointcloud.  Not sure if you're interested.  If so, I can send a pull request?

**Comment by dabulla** [comment]
Adding points to it? Yes, I'd be interested to integrate it. Go ahead. I use the point cloud renderer in a project that will run at least another 1,5 years. In that time I want to improve it quite a bit and work on it from time to time. Maybe I even end up adding octree/out-of-core support. Help is greatly appreciated.
