### ISSUE TITLE
BSD or Apache

### ISSUE THREAD

**Issue by garybradski** [MASKOR/Qt3DPointcloudRenderer#4]
This seemed like a good starting point for getting into opengl and qt, but GNU license means it can only be used in student projects since it contaminates the entire codebase making this code basically useless. 

Since this isn't some super advanced, secret stuff that you later want to make a commercial and useless version of, is there a reason it can't be switched to BSD or Apache license?

**Comment by dabulla** [comment]
Added LGPL. I wanted to choose the same license as qt opensource. You can dynamically link to it and please contribute helpful changes to library itself.
Hope this helps and thanks for the pointer.
